# Generated by Django 4.2.6 on 2023-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='env_name',
            new_name='environment_name',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
