# Generated by Django 4.2.6 on 2023-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_remove_post_description_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='environment_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
