# Generated by Django 4.2.6 on 2023-11-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_alter_post_environment_name_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='action_space',
            new_name='actions_number',
        ),
    ]
