# Generated by Django 4.2.6 on 2023-11-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0008_comment_delete_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
    ]
