# Generated by Django 4.2.6 on 2023-11-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0009_rename_comment_date_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('post', models.ManyToManyField(to='environments.post')),
            ],
        ),
    ]
