# Generated by Django 4.2.6 on 2023-11-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0010_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='post',
            new_name='posts',
        ),
    ]
